"""
PDF Report Generator
----------------------
Generates a downloadable eligibility report using fpdf2.
Returns the PDF as bytes.
"""

import io
from datetime import date
from typing import Dict, Any, List

from fpdf import FPDF, XPos, YPos


SAFFRON = (255, 153, 51)
GREEN   = (19, 136, 8)
NAVY    = (15, 52, 96)
GRAY    = (100, 100, 100)
LIGHT   = (245, 247, 250)


class EligibilityReport(FPDF):
    def __init__(self, user_name: str):
        super().__init__()
        self.user_name = user_name
        self.set_margins(15, 15, 15)
        self.set_auto_page_break(auto=True, margin=15)

    def header(self):
        # Tricolor stripe
        self.set_fill_color(*SAFFRON)
        self.rect(0, 0, 210, 4, "F")
        self.set_fill_color(255, 255, 255)
        self.rect(0, 4, 210, 4, "F")
        self.set_fill_color(*GREEN)
        self.rect(0, 8, 210, 4, "F")

        self.set_y(15)
        self.set_font("Helvetica", "B", 18)
        self.set_text_color(*NAVY)
        self.cell(0, 8, "SaralSewa - AI Governance Copilot", new_x=XPos.LMARGIN, new_y=YPos.NEXT, align="C")
        self.set_font("Helvetica", "", 10)
        self.set_text_color(*GRAY)
        self.cell(0, 5, "CivicMatch Eligibility and Readiness Report", new_x=XPos.LMARGIN, new_y=YPos.NEXT, align="C")
        self.ln(3)

    def footer(self):
        self.set_y(-13)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(*GRAY)
        self.cell(0, 5, f"Page {self.page_no()} | Generated by SaralSewa MVP | {date.today().strftime('%d %b %Y')}", align="C")

    def section_title(self, title: str):
        self.set_font("Helvetica", "B", 12)
        self.set_text_color(*NAVY)
        self.set_fill_color(*LIGHT)
        self.cell(0, 8, f"  {title}", new_x=XPos.LMARGIN, new_y=YPos.NEXT, fill=True)
        self.ln(2)

    def kv_row(self, key: str, value: str, bold_value: bool = False):
        self.set_font("Helvetica", "", 9)
        self.set_text_color(*GRAY)
        self.cell(50, 6, key + ":", new_x=XPos.RIGHT)
        if bold_value:
            self.set_font("Helvetica", "B", 9)
        self.set_text_color(30, 30, 30)
        self.cell(0, 6, value, new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    def bullet(self, text: str, color=(50, 50, 50)):
        self.set_font("Helvetica", "", 9)
        self.set_text_color(*color)
        self.cell(6, 5, chr(149))
        self.multi_cell(0, 5, text)


def generate_pdf_report(
    user_profile: Dict[str, Any],
    match_results: List[Dict[str, Any]],
) -> bytes:
    pdf = EligibilityReport(user_profile.get("name", "Applicant"))
    pdf.add_page()

    # ── User Profile ──────────────────────────────────────────────────────────
    pdf.section_title("Applicant Profile")
    pdf.kv_row("Name", user_profile.get("name", "—"), bold_value=True)
    pdf.kv_row("Age", str(user_profile.get("age", "—")))
    pdf.kv_row("Gender", user_profile.get("gender", "—").title())
    pdf.kv_row("Annual Income", f"Rs. {user_profile.get('income', 0):,}")
    pdf.kv_row("Occupation", user_profile.get("occupation", "—").replace("_", " ").title())
    pdf.kv_row("State", user_profile.get("state", "—"))
    pdf.kv_row("BPL Card", "Yes" if user_profile.get("is_bpl") else "No")
    pdf.kv_row("Report Date", date.today().strftime("%d %B %Y"))
    pdf.ln(4)

    # ── Summary ───────────────────────────────────────────────────────────────
    eligible   = [r for r in match_results if r.get("is_eligible")]
    ineligible = [r for r in match_results if not r.get("is_eligible")]

    pdf.section_title("Eligibility Summary")
    pdf.kv_row("Total Schemes Checked", str(len(match_results)))
    pdf.kv_row("Eligible", str(len(eligible)), bold_value=True)
    pdf.kv_row("Not Eligible", str(len(ineligible)))
    if match_results:
        top = match_results[0]["scheme_name"]
        pdf.kv_row("Top Recommendation", top, bold_value=True)
    pdf.ln(4)

    # ── Per-Scheme Results ────────────────────────────────────────────────────
    pdf.section_title("Detailed Scheme Results")

    for r in match_results:
        eligible_flag = r.get("is_eligible", False)
        score = r.get("readiness_score", 0)

        # Scheme header
        pdf.set_font("Helvetica", "B", 10)
        status_color = GREEN if eligible_flag else (180, 0, 0)
        pdf.set_text_color(*status_color)
        status_text = "ELIGIBLE" if eligible_flag else "NOT ELIGIBLE"
        pdf.cell(0, 7,
            f"#{r.get('relevance_rank','')}  {r.get('scheme_name','')}  [{status_text}]",
            new_x=XPos.LMARGIN, new_y=YPos.NEXT,
        )

        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(*GRAY)
        pdf.cell(0, 5, f"Benefit: {r.get('benefit','')}  |  Readiness Score: {score}%",
                 new_x=XPos.LMARGIN, new_y=YPos.NEXT)

        if r.get("ineligibility_reasons"):
            pdf.set_font("Helvetica", "B", 8)
            pdf.set_text_color(180, 0, 0)
            pdf.cell(0, 5, "  Criteria Not Met:", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            for reason in r["ineligibility_reasons"]:
                pdf.bullet(reason, color=(180, 0, 0))

        if r.get("missing_documents"):
            pdf.set_font("Helvetica", "B", 8)
            pdf.set_text_color(*NAVY)
            pdf.cell(0, 5, "  Missing Documents:", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            for doc in r["missing_documents"]:
                pdf.bullet(doc, color=(80, 80, 130))

        if eligible_flag and r.get("action_steps"):
            pdf.set_font("Helvetica", "B", 8)
            pdf.set_text_color(*GREEN)
            pdf.cell(0, 5, "  Next Steps:", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            for step in r["action_steps"][:4]:
                if step.strip():
                    pdf.bullet(step.strip(), color=(10, 100, 10))

        pdf.ln(3)
        pdf.set_draw_color(220, 220, 220)
        pdf.line(15, pdf.get_y(), 195, pdf.get_y())
        pdf.ln(3)

    return bytes(pdf.output())